services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=train_management'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=secret'
      - 'MYSQL_USER=adminDb'
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/var/lib/mysql'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data'
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
volumes:
  mysql_data:
  redis_data:

