const USER_ROLES = {
  ADMIN: 'ADMIN',
  USER: 'USER',
};

const ROW_PER_PAGE = 8;

const BOOKING_TYPE = {
  ONE_WAY: 'ONE_WAY',
  ROUND_TRIP: 'ROUND_TRIP',
};

export { USER_ROLES, ROW_PER_PAGE, BOOKING_TYPE };
