const USER_ROLES = {
  ADMIN: 'ADMIN',
  USER: 'USER',
};

const ROW_PER_PAGE = 8;

const BOOKING_TYPE = {
  ONE_WAY: 'ONE_WAY',
  ROUND_TRIP: 'ROUND_TRIP',
};

const SEAT_TYPE = {
  SELECTED: 'SELECTED',
  AVAILABLE: 'AVAILABLE',
  UNAVAILABLE: 'UNAVAILABLE',
};

export { USER_ROLES, ROW_PER_PAGE, BOOKING_TYPE, SEAT_TYPE };
