server:
  http2:
    enabled: true
  port: 3001 # change to your port you want

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/train_management
    username: root  # change to your username
    password:  # change to your password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create  # if you have problems with db, change to 'create' at the first time you run application
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: lequanphat2003@gmail.com
    password: ewnj fojp lfau vfsx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  show-actuator: true

management:
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: INFO
    com.backend.railwaybookingsystem: INFO

## FIXME : Customize JWT token and Swagger information for your application

jwt:
  secretKey: secret
  issuer: nhatsinh.id.vn
  expirationMinute: 10
  expirationRefreshMinute: 30

swagger:
  contact-name: Tran Nhat Sinh
  contact-mail: transinh085@gmail.com
  contact-url: https://nhatsinh.id.vn
  app-name: Railway Booking System
  app-description: "Spring Boot Boilerplate is a starter kit. This project includes : Spring Boot(3.3.1), Spring Data JPA, Spring Validation, Spring Security + JWT Token, PostgreSQL, Mapstruct, Lombok, Swagger (Open API)"
  app-version: 3.3.1
  app-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  app-license: Apache 2.0
