server:
  http2:
    enabled: true
  port: 3001 # change to your port you want

frontend:
  url: http://localhost:3000 # change to your frontend url

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/train_management
    username: root # change to your username
    password: secret # change to your password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create # if you have problems with db, change to 'create' at the first time you run application
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always # always khi ddl-auto = create, never khi ddl-auto = update
      data-locations: classpath:/procedures.sql, classpath:/data.sql
      separator: ^;

  mail:
    host: smtp.gmail.com
    port: 587
    username: lequanphat2003@gmail.com
    password: ewnj fojp lfau vfsx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 622494579867-8igtkg8u1i20sllcgvc01jf80gcrumff.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "${GOOGLE_REDIRECT_URI:http://localhost:3001/api/oauth2/google/callback}"
            scope: openid, profile, email
          facebook:
            client-id: 423573474136909
            client-secret: 26a51e7f5a2c9e3fd32fddc874015b34
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 10000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest




springdoc:
  show-actuator: true

management:
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework:
        web:
          socket: INFO
        messaging: INFO
        core: INFO
    com.backend.railwaybookingsystem: INFO

## FIXME : Customize JWT token and Swagger information for your application

jwt:
  secretKey: secret
  issuer: nhatsinh.id.vn
  expirationMinute: 30
  expirationRefreshMinute: 10080 # 7 days

swagger:
  contact-name: Tran Nhat Sinh
  contact-mail: transinh085@gmail.com
  contact-url: https://nhatsinh.id.vn
  app-name: Railway Booking System
  app-description: "Railway Booking System is built on Spring Boot + React"
  app-version: 3.3.1
  app-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  app-license: Apache 2.0

paypal:
  client:
    id: AQLsHjZe-il61FgoSzNjDpBPMA9NWS8jFCty4unSn8qLc1xcW1NvZ2Vz9_sZokkzf1CCDfAnh8EyqPyQ
    secret: EILGMwYVy8_sMmbKpMwJxPtYCRdkqWyWM40N45lwzfJqh5f2mkmMZNDRo9Z7DuMzzCfKyBGZjs25ed-a
  mode: sandbox